<?php


class Master_industryTableSeeder extends Seeder
{

	public function run()
	{
	    DB::table('m_industry')->delete();
	    M_Industry::create( array('id' => '1','en' => 'Accounting','in' => 'Akuntansi') );
	    M_Industry::create( array('id' => '2','en' => 'Airlines/Aviation','in' => 'Penerbangan Komersil') );
	    M_Industry::create( array('id' => '3','en' => 'Alternative Medicine','in' => 'Pengobatan Alternatif') );
	    M_Industry::create( array('id' => '4','en' => 'Animation','in' => 'Animasi') );
	    M_Industry::create( array('id' => '5','en' => 'Apparel &amp; Fashion','in' => 'Busana &amp; Fashion') );
	    M_Industry::create( array('id' => '6','en' => 'Architecture &amp; Planning','in' => 'Arsitektur &amp; Perencanaan') );
	    M_Industry::create( array('id' => '7','en' => 'Arts &amp; Crafts','in' => 'Seni &amp; Kerajinan') );
	    M_Industry::create( array('id' => '8','en' => 'Automotive','in' => 'Otomotif') );
	    M_Industry::create( array('id' => '9','en' => 'Aviation &amp; Aerospace','in' => 'Penerbangan Angkasa Luar') );
	    M_Industry::create( array('id' => '10','en' => 'Banking','in' => 'Perbankan') );
	    M_Industry::create( array('id' => '11','en' => 'Biotechnology','in' => 'Bioteknologi') );
	    M_Industry::create( array('id' => '12','en' => 'Broadcast Media','in' => 'Media Penyiaran') );
	    M_Industry::create( array('id' => '13','en' => 'Building Materials','in' => 'Bahan Bangunan') );
	    M_Industry::create( array('id' => '14','en' => 'Business Supplies &amp; Equipment','in' => 'Peralatan Kantor') );
	    M_Industry::create( array('id' => '15','en' => 'Capital Markets','in' => 'Pasar Uang') );
	    M_Industry::create( array('id' => '16','en' => 'Chemicals','in' => 'Kimia') );
	    M_Industry::create( array('id' => '17','en' => 'Civic &amp; Social Organization','in' => 'LSM') );
	    M_Industry::create( array('id' => '18','en' => 'Civil Engineering','in' => 'Teknik Sipil') );
	    M_Industry::create( array('id' => '19','en' => 'Commercial Real Estate','in' => 'Perumahan Komersil') );
	    M_Industry::create( array('id' => '20','en' => 'Computer Games','in' => 'Permainan Komputer') );
	    M_Industry::create( array('id' => '21','en' => 'Computer Hardware','in' => 'Perangkat Komputer') );
	    M_Industry::create( array('id' => '22','en' => 'Computer Networking','in' => 'Jaringan') );
	    M_Industry::create( array('id' => '23','en' => 'Computer Software','in' => 'Perangkat Lunak') );
	    M_Industry::create( array('id' => '24','en' => 'Construction','in' => 'Konstruksi') );
	    M_Industry::create( array('id' => '25','en' => 'Consumer Electronics','in' => 'Elektronik Rumah Tangga') );
	    M_Industry::create( array('id' => '26','en' => 'Consumer Goods','in' => 'Perlengkapan Rumah Tangga') );
	    M_Industry::create( array('id' => '27','en' => 'Cosmetics','in' => 'Kosmetika') );
	    M_Industry::create( array('id' => '28','en' => 'Dairy','in' => 'Produk Susu') );
	    M_Industry::create( array('id' => '29','en' => 'Defense &amp; Space','in' => 'Pertahanan Udara') );
	    M_Industry::create( array('id' => '30','en' => 'Design','in' => 'Design') );
	    M_Industry::create( array('id' => '31','en' => 'Education Management','in' => 'Manajemen Pendidikan') );
	    M_Industry::create( array('id' => '32','en' => 'E-learning','in' => 'E-Learning') );
	    M_Industry::create( array('id' => '33','en' => 'Electrical &amp; Electronic Manufacturing','in' => 'Kelistrikan &amp; Manufaktur Elektronik') );
	    M_Industry::create( array('id' => '34','en' => 'Entertainment','in' => 'Hiburan') );
	    M_Industry::create( array('id' => '35','en' => 'Events Services','in' => 'Events') );
	    M_Industry::create( array('id' => '36','en' => 'Facilities Services','in' => 'Sewa Fasilitas') );
	    M_Industry::create( array('id' => '37','en' => 'Farming','in' => 'Pertanian') );
	    M_Industry::create( array('id' => '38','en' => 'Financial Services','in' => 'Jasa Finansial') );
	    M_Industry::create( array('id' => '39','en' => 'Fine Art','in' => 'Seni Murni') );
	    M_Industry::create( array('id' => '40','en' => 'Fishery','in' => 'Perikanan') );
	    M_Industry::create( array('id' => '41','en' => 'Food &amp; Beverages','in' => 'Makanan &amp; Minuman') );
	    M_Industry::create( array('id' => '42','en' => 'Food Production','in' => 'Produsen Makanan') );
	    M_Industry::create( array('id' => '43','en' => 'Fundraising','in' => 'Pendanaan') );
	    M_Industry::create( array('id' => '44','en' => 'Furniture','in' => 'Furnitur') );
	    M_Industry::create( array('id' => '45','en' => 'Glass, Ceramics &amp; Concrete','in' => 'Kaca, Keramik &amp; Beton') );
	    M_Industry::create( array('id' => '46','en' => 'Government Administration','in' => 'Pemerintahan') );
	    M_Industry::create( array('id' => '47','en' => 'Graphic Design','in' => 'Design Grafis') );
	    M_Industry::create( array('id' => '48','en' => 'Health, Wellness &amp; Fitness','in' => 'Kesehatan') );
	    M_Industry::create( array('id' => '49','en' => 'Higher Education','in' => 'Perguruan Tinggi') );
	    M_Industry::create( array('id' => '50','en' => 'Hospital &amp; Health Care','in' => 'Rumah Sakit &amp; Klinik') );
	    M_Industry::create( array('id' => '51','en' => 'Hospitality','in' => 'Hospitality') );
	    M_Industry::create( array('id' => '52','en' => 'Human Resources','in' => 'Sumberdaya Manusia') );
	    M_Industry::create( array('id' => '53','en' => 'Import &amp; Export','in' => 'Impor &amp; Ekspor') );
	    M_Industry::create( array('id' => '54','en' => 'Industrial Automation','in' => 'Otomasi Industri') );
	    M_Industry::create( array('id' => '55','en' => 'Information Services','in' => 'Informasi') );
	    M_Industry::create( array('id' => '56','en' => 'Information Technology &amp; Services','in' => 'Teknologi Informasi') );
	    M_Industry::create( array('id' => '57','en' => 'Insurance','in' => 'Asuransi') );
	    M_Industry::create( array('id' => '58','en' => 'International Affairs','in' => 'Hubungan Internasional') );
	    M_Industry::create( array('id' => '59','en' => 'International Trade &amp; Development','in' => 'Perdagangan Internasional') );
	    M_Industry::create( array('id' => '60','en' => 'Internet','in' => 'Internet') );
	    M_Industry::create( array('id' => '61','en' => 'Investment Banking/Venture','in' => 'Permodalan') );
	    M_Industry::create( array('id' => '62','en' => 'Investment Management','in' => 'Manajemen Investasi') );
	    M_Industry::create( array('id' => '63','en' => 'Judiciary','in' => 'Kehakiman') );
	    M_Industry::create( array('id' => '64','en' => 'Law Enforcement','in' => 'Penegak Hukum') );
	    M_Industry::create( array('id' => '65','en' => 'Law Practice','in' => 'Parktek Hukum') );
	    M_Industry::create( array('id' => '66','en' => 'Legal Services','in' => 'Jasa Hukum') );
	    M_Industry::create( array('id' => '67','en' => 'Leisure &amp; Travel','in' => 'Liburan &amp; Perjalanan') );
	    M_Industry::create( array('id' => '68','en' => 'Libraries','in' => 'Perpustakaan') );
	    M_Industry::create( array('id' => '69','en' => 'Logistics &amp; Supply Chain','in' => 'Logistik') );
	    M_Industry::create( array('id' => '70','en' => 'Luxury Goods &amp; Jewelry','in' => 'Perhiasan') );
	    M_Industry::create( array('id' => '71','en' => 'Machinery','in' => 'Mesin') );
	    M_Industry::create( array('id' => '72','en' => 'Management Consulting','in' => 'Bisnis Konsultan') );
	    M_Industry::create( array('id' => '73','en' => 'Maritime','in' => 'Kelautan') );
	    M_Industry::create( array('id' => '74','en' => 'Marketing &amp; Advertising','in' => 'Marketing &amp; Periklanan') );
	    M_Industry::create( array('id' => '75','en' => 'Market Research','in' => 'Riset Pasar') );
	    M_Industry::create( array('id' => '76','en' => 'Mechanical or Industrial Engineering','in' => 'Mekanik / Industri') );
	    M_Industry::create( array('id' => '77','en' => 'Media Production','in' => 'Produksi Media') );
	    M_Industry::create( array('id' => '78','en' => 'Medical Device','in' => 'Alat Kesehatan') );
	    M_Industry::create( array('id' => '79','en' => 'Medical Practice','in' => 'Praktek Kesehatan') );
	    M_Industry::create( array('id' => '80','en' => 'Military','in' => 'Militer') );
	    M_Industry::create( array('id' => '81','en' => 'Mining &amp; Metals','in' => 'Tambang &amp; Besi') );
	    M_Industry::create( array('id' => '82','en' => 'Motion Pictures &amp; Film','in' => 'Perfilman') );
	    M_Industry::create( array('id' => '83','en' => 'Museums &amp; Institutions','in' => 'Institusi &amp; Museum') );
	    M_Industry::create( array('id' => '84','en' => 'Music','in' => 'Musik') );
	    M_Industry::create( array('id' => '85','en' => 'Newspapers','in' => 'Koran') );
	    M_Industry::create( array('id' => '86','en' => 'Nonprofit Organization Management','in' => 'Lembaga Swadaya Masyarakat') );
	    M_Industry::create( array('id' => '87','en' => 'Oil &amp; Energy','in' => 'Minyak Bumi &amp; Energi') );
	    M_Industry::create( array('id' => '88','en' => 'Online Publishing','in' => 'Penerbit Online') );
	    M_Industry::create( array('id' => '89','en' => 'Package/Freight Delivery','in' => 'Pengiriman Barang / Ekspedisi') );
	    M_Industry::create( array('id' => '90','en' => 'Packaging &amp; Containers','in' => 'Pengemasan') );
	    M_Industry::create( array('id' => '91','en' => 'Paper &amp; Forest Products','in' => 'Produk Kertas') );
	    M_Industry::create( array('id' => '92','en' => 'Performing Arts','in' => 'Pertunjukan') );
	    M_Industry::create( array('id' => '93','en' => 'Pharmaceuticals','in' => 'Farmasi') );
	    M_Industry::create( array('id' => '94','en' => 'Photography','in' => 'Fotografi') );
	    M_Industry::create( array('id' => '95','en' => 'Plastics','in' => 'Plastik') );
	    M_Industry::create( array('id' => '96','en' => 'Political Organization','in' => 'Organisasi Politik') );
	    M_Industry::create( array('id' => '97','en' => 'Printing','in' => 'Percetakan') );
	    M_Industry::create( array('id' => '98','en' => 'Professional Training','in' => 'Pelatihan') );
	    M_Industry::create( array('id' => '99','en' => 'Public Relations','in' => 'PR') );
	    M_Industry::create( array('id' => '100','en' => 'Public Safety','in' => 'Keselamatan Umum') );
	    M_Industry::create( array('id' => '101','en' => 'Publishing','in' => 'Penerbitan') );
	    M_Industry::create( array('id' => '102','en' => 'Ranching','in' => 'Peternakan') );
	    M_Industry::create( array('id' => '103','en' => 'Real Estate','in' => 'Perumahan') );
	    M_Industry::create( array('id' => '104','en' => 'Recreational Facilities &amp; Services','in' => 'Sarana Rekreasi') );
	    M_Industry::create( array('id' => '105','en' => 'Religious Institutions','in' => 'Institusi Agama') );
	    M_Industry::create( array('id' => '106','en' => 'Renewables &amp; Environment','in' => 'Daur Ulang &amp; Lingkungan') );
	    M_Industry::create( array('id' => '107','en' => 'Research','in' => 'Riset') );
	    M_Industry::create( array('id' => '108','en' => 'Restaurants','in' => 'Restauran') );
	    M_Industry::create( array('id' => '109','en' => 'Retail','in' => 'Penjualan') );
	    M_Industry::create( array('id' => '110','en' => 'Security &amp; Investigations','in' => 'Keamanan &amp; Investigasi') );
	    M_Industry::create( array('id' => '111','en' => 'Shipbuilding','in' => 'Perkapalan') );
	    M_Industry::create( array('id' => '112','en' => 'Sporting Goods','in' => 'Alat Olahraga') );
	    M_Industry::create( array('id' => '113','en' => 'Sports','in' => 'Olahraga') );
	    M_Industry::create( array('id' => '114','en' => 'Staffing &amp; Recruiting','in' => 'Staff &amp; Rekrutmen') );
	    M_Industry::create( array('id' => '115','en' => 'Supermarkets','in' => 'Supermarket') );
	    M_Industry::create( array('id' => '116','en' => 'Telecommunications','in' => 'Telekomunikasi') );
	    M_Industry::create( array('id' => '117','en' => 'Textiles','in' => 'Tekstil') );
	    M_Industry::create( array('id' => '118','en' => 'Tobacco','in' => 'Tembakau') );
	    M_Industry::create( array('id' => '119','en' => 'Translation &amp; Localization','in' => 'Penerjemah') );
	    M_Industry::create( array('id' => '120','en' => 'Transportation/Trucking/Railroad','in' => 'Transportasi') );
	    M_Industry::create( array('id' => '121','en' => 'Utilities','in' => 'Peralatan') );
	    M_Industry::create( array('id' => '122','en' => 'Venture Capital','in' => 'Venture Capital') );
	    M_Industry::create( array('id' => '123','en' => 'Veterinary','in' => 'Dokter Hewan') );
	    M_Industry::create( array('id' => '124','en' => 'Warehousing','in' => 'Pergudangan') );
	    M_Industry::create( array('id' => '125','en' => 'Wholesale','in' => 'Grosir / Perkulakan') );
	    M_Industry::create( array('id' => '126','en' => 'Writing &amp; Editing','in' => 'Penulis &amp; Editor') );
	}

}